/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // ── The Modern Archivist palette (canonical from DESIGN.md) ──
        "primary":                   "#041627",
        "on-primary":                "#ffffff",
        "primary-container":         "#1a2b3c",
        "on-primary-container":      "#8192a7",
        "primary-fixed":             "#d2e4fb",
        "primary-fixed-dim":         "#b7c8de",
        "on-primary-fixed":          "#0b1d2d",
        "on-primary-fixed-variant":  "#38485a",
        "inverse-primary":           "#b7c8de",

        "secondary":                 "#735c00",
        "on-secondary":              "#ffffff",
        "secondary-container":       "#fed65b",
        "on-secondary-container":    "#745c00",
        "secondary-fixed":           "#ffe088",
        "secondary-fixed-dim":       "#e9c349",
        "on-secondary-fixed":        "#241a00",
        "on-secondary-fixed-variant":"#574500",

        "tertiary":                  "#211200",
        "on-tertiary":               "#ffffff",
        "tertiary-container":        "#38260b",
        "on-tertiary-container":     "#a88c69",
        "tertiary-fixed":            "#feddb5",
        "tertiary-fixed-dim":        "#e1c29b",
        "on-tertiary-fixed":         "#281802",
        "on-tertiary-fixed-variant": "#584326",

        "surface":                   "#f4f1ea",
        "surface-bright":            "#fcf9f2",
        "surface-dim":               "#dcdad3",
        "surface-container-lowest":  "#ffffff",
        "surface-container-low":     "#f6f3ec",
        "surface-container":         "#f1eee7",
        "surface-container-high":    "#ebe8e1",
        "surface-container-highest": "#e5e2db",
        "surface-variant":           "#e5e2db",
        "surface-tint":              "#4f6073",

        "on-surface":                "#1c1c18",
        "on-surface-variant":        "#44474c",
        "on-background":             "#1c1c18",
        "background":                "#f4f1ea",
        "inverse-surface":           "#31312c",
        "inverse-on-surface":        "#f3f0e9",

        "outline":                   "#74777d",
        "outline-variant":           "#c4c6cd",

        "error":                     "#ba1a1a",
        "on-error":                  "#ffffff",
        "error-container":           "#ffdad6",
        "on-error-container":        "#93000a",
      },
      fontFamily: {
        "headline": ["Newsreader", "Georgia", "serif"],
        "body":     ["Inter", "system-ui", "sans-serif"],
        "label":    ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm:      "0.125rem",
        md:      "0.375rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        full:    "9999px",
      },
      boxShadow: {
        ambient: "0 12px 40px rgba(28, 28, 24, 0.06)",
        card:    "0 4px 16px rgba(28, 28, 24, 0.04)",
        panel:   "0 2px 8px rgba(28, 28, 24, 0.05)",
      },
      fontSize: {
        "display-lg":  ["3.5rem",   { lineHeight: "1.15", letterSpacing: "-0.02em" }],
        "display-md":  ["2.75rem",  { lineHeight: "1.2",  letterSpacing: "-0.015em" }],
        "headline-lg": ["2rem",     { lineHeight: "1.3",  letterSpacing: "-0.01em" }],
        "headline-md": ["1.75rem",  { lineHeight: "1.35", letterSpacing: "-0.01em" }],
        "headline-sm": ["1.5rem",   { lineHeight: "1.4" }],
        "title-lg":    ["1.25rem",  { lineHeight: "1.45" }],
        "title-md":    ["1rem",     { lineHeight: "1.5" }],
        "title-sm":    ["0.875rem", { lineHeight: "1.5",  letterSpacing: "0.01em" }],
        "body-lg":     ["1rem",     { lineHeight: "1.6" }],
        "body-md":     ["0.875rem", { lineHeight: "1.55" }],
        "body-sm":     ["0.75rem",  { lineHeight: "1.5" }],
        "label-lg":    ["0.875rem", { lineHeight: "1.4",  letterSpacing: "0.1em" }],
        "label-md":    ["0.75rem",  { lineHeight: "1.3",  letterSpacing: "0.1em" }],
        "label-sm":    ["0.6875rem",{ lineHeight: "1.3",  letterSpacing: "0.12em" }],
      },
    },
  },
  plugins: [],
};
